/**
 * ISO 3166-1 alpha-2 country codes and names for searchable selects.
 * Source: ISO-3166-Countries-with-Regional-Codes (slim-2).
 */

export type CountryOption = { code: string; name: string };

const RAW: { name: string; "alpha-2": string }[] = [
  { name: "Afghanistan", "alpha-2": "AF" },
  { name: "Albania", "alpha-2": "AL" },
  { name: "Algeria", "alpha-2": "DZ" },
  { name: "Argentina", "alpha-2": "AR" },
  { name: "Australia", "alpha-2": "AU" },
  { name: "Austria", "alpha-2": "AT" },
  { name: "Bahrain", "alpha-2": "BH" },
  { name: "Bangladesh", "alpha-2": "BD" },
  { name: "Belgium", "alpha-2": "BE" },
  { name: "Brazil", "alpha-2": "BR" },
  { name: "Canada", "alpha-2": "CA" },
  { name: "China", "alpha-2": "CN" },
  { name: "Colombia", "alpha-2": "CO" },
  { name: "Egypt", "alpha-2": "EG" },
  { name: "Ethiopia", "alpha-2": "ET" },
  { name: "France", "alpha-2": "FR" },
  { name: "Germany", "alpha-2": "DE" },
  { name: "Ghana", "alpha-2": "GH" },
  { name: "India", "alpha-2": "IN" },
  { name: "Indonesia", "alpha-2": "ID" },
  { name: "Iran, Islamic Republic of", "alpha-2": "IR" },
  { name: "Iraq", "alpha-2": "IQ" },
  { name: "Ireland", "alpha-2": "IE" },
  { name: "Israel", "alpha-2": "IL" },
  { name: "Italy", "alpha-2": "IT" },
  { name: "Japan", "alpha-2": "JP" },
  { name: "Jordan", "alpha-2": "JO" },
  { name: "Kenya", "alpha-2": "KE" },
  { name: "Kuwait", "alpha-2": "KW" },
  { name: "Lebanon", "alpha-2": "LB" },
  { name: "Malaysia", "alpha-2": "MY" },
  { name: "Mexico", "alpha-2": "MX" },
  { name: "Morocco", "alpha-2": "MA" },
  { name: "Netherlands, Kingdom of the", "alpha-2": "NL" },
  { name: "Nigeria", "alpha-2": "NG" },
  { name: "Oman", "alpha-2": "OM" },
  { name: "Pakistan", "alpha-2": "PK" },
  { name: "Palestine, State of", "alpha-2": "PS" },
  { name: "Philippines", "alpha-2": "PH" },
  { name: "Poland", "alpha-2": "PL" },
  { name: "Qatar", "alpha-2": "QA" },
  { name: "Russian Federation", "alpha-2": "RU" },
  { name: "Saudi Arabia", "alpha-2": "SA" },
  { name: "South Africa", "alpha-2": "ZA" },
  { name: "Spain", "alpha-2": "ES" },
  { name: "Sudan", "alpha-2": "SD" },
  { name: "Sweden", "alpha-2": "SE" },
  { name: "Switzerland", "alpha-2": "CH" },
  { name: "Syrian Arab Republic", "alpha-2": "SY" },
  { name: "Tunisia", "alpha-2": "TN" },
  { name: "Türkiye", "alpha-2": "TR" },
  { name: "Uganda", "alpha-2": "UG" },
  { name: "Ukraine", "alpha-2": "UA" },
  { name: "United Arab Emirates", "alpha-2": "AE" },
  { name: "United Kingdom of Great Britain and Northern Ireland", "alpha-2": "GB" },
  { name: "United States of America", "alpha-2": "US" },
  { name: "Yemen", "alpha-2": "YE" },
  // Extended list (common + rest)
  { name: "Åland Islands", "alpha-2": "AX" },
  { name: "American Samoa", "alpha-2": "AS" },
  { name: "Andorra", "alpha-2": "AD" },
  { name: "Angola", "alpha-2": "AO" },
  { name: "Antigua and Barbuda", "alpha-2": "AG" },
  { name: "Armenia", "alpha-2": "AM" },
  { name: "Azerbaijan", "alpha-2": "AZ" },
  { name: "Belarus", "alpha-2": "BY" },
  { name: "Belize", "alpha-2": "BZ" },
  { name: "Benin", "alpha-2": "BJ" },
  { name: "Bosnia and Herzegovina", "alpha-2": "BA" },
  { name: "Botswana", "alpha-2": "BW" },
  { name: "Bulgaria", "alpha-2": "BG" },
  { name: "Burkina Faso", "alpha-2": "BF" },
  { name: "Burundi", "alpha-2": "BI" },
  { name: "Cabo Verde", "alpha-2": "CV" },
  { name: "Cambodia", "alpha-2": "KH" },
  { name: "Cameroon", "alpha-2": "CM" },
  { name: "Chad", "alpha-2": "TD" },
  { name: "Chile", "alpha-2": "CL" },
  { name: "Congo", "alpha-2": "CG" },
  { name: "Congo, Democratic Republic of the", "alpha-2": "CD" },
  { name: "Costa Rica", "alpha-2": "CR" },
  { name: "Côte d'Ivoire", "alpha-2": "CI" },
  { name: "Croatia", "alpha-2": "HR" },
  { name: "Cuba", "alpha-2": "CU" },
  { name: "Cyprus", "alpha-2": "CY" },
  { name: "Czechia", "alpha-2": "CZ" },
  { name: "Denmark", "alpha-2": "DK" },
  { name: "Djibouti", "alpha-2": "DJ" },
  { name: "Dominican Republic", "alpha-2": "DO" },
  { name: "Ecuador", "alpha-2": "EC" },
  { name: "El Salvador", "alpha-2": "SV" },
  { name: "Eritrea", "alpha-2": "ER" },
  { name: "Estonia", "alpha-2": "EE" },
  { name: "Eswatini", "alpha-2": "SZ" },
  { name: "Fiji", "alpha-2": "FJ" },
  { name: "Finland", "alpha-2": "FI" },
  { name: "Gabon", "alpha-2": "GA" },
  { name: "Gambia", "alpha-2": "GM" },
  { name: "Georgia", "alpha-2": "GE" },
  { name: "Greece", "alpha-2": "GR" },
  { name: "Guatemala", "alpha-2": "GT" },
  { name: "Guinea", "alpha-2": "GN" },
  { name: "Haiti", "alpha-2": "HT" },
  { name: "Honduras", "alpha-2": "HN" },
  { name: "Hong Kong", "alpha-2": "HK" },
  { name: "Hungary", "alpha-2": "HU" },
  { name: "Iceland", "alpha-2": "IS" },
  { name: "Kazakhstan", "alpha-2": "KZ" },
  { name: "Korea, Republic of", "alpha-2": "KR" },
  { name: "Kyrgyzstan", "alpha-2": "KG" },
  { name: "Lao People's Democratic Republic", "alpha-2": "LA" },
  { name: "Latvia", "alpha-2": "LV" },
  { name: "Libya", "alpha-2": "LY" },
  { name: "Lithuania", "alpha-2": "LT" },
  { name: "Luxembourg", "alpha-2": "LU" },
  { name: "Madagascar", "alpha-2": "MG" },
  { name: "Malawi", "alpha-2": "MW" },
  { name: "Maldives", "alpha-2": "MV" },
  { name: "Mali", "alpha-2": "ML" },
  { name: "Malta", "alpha-2": "MT" },
  { name: "Mauritania", "alpha-2": "MR" },
  { name: "Mauritius", "alpha-2": "MU" },
  { name: "Moldova, Republic of", "alpha-2": "MD" },
  { name: "Mongolia", "alpha-2": "MN" },
  { name: "Montenegro", "alpha-2": "ME" },
  { name: "Mozambique", "alpha-2": "MZ" },
  { name: "Myanmar", "alpha-2": "MM" },
  { name: "Namibia", "alpha-2": "NA" },
  { name: "Nepal", "alpha-2": "NP" },
  { name: "New Zealand", "alpha-2": "NZ" },
  { name: "Niger", "alpha-2": "NE" },
  { name: "North Macedonia", "alpha-2": "MK" },
  { name: "Norway", "alpha-2": "NO" },
  { name: "Panama", "alpha-2": "PA" },
  { name: "Paraguay", "alpha-2": "PY" },
  { name: "Peru", "alpha-2": "PE" },
  { name: "Portugal", "alpha-2": "PT" },
  { name: "Romania", "alpha-2": "RO" },
  { name: "Rwanda", "alpha-2": "RW" },
  { name: "Senegal", "alpha-2": "SN" },
  { name: "Serbia", "alpha-2": "RS" },
  { name: "Singapore", "alpha-2": "SG" },
  { name: "Slovakia", "alpha-2": "SK" },
  { name: "Slovenia", "alpha-2": "SI" },
  { name: "Somalia", "alpha-2": "SO" },
  { name: "South Sudan", "alpha-2": "SS" },
  { name: "Sri Lanka", "alpha-2": "LK" },
  { name: "Tanzania, United Republic of", "alpha-2": "TZ" },
  { name: "Thailand", "alpha-2": "TH" },
  { name: "Togo", "alpha-2": "TG" },
  { name: "Turkmenistan", "alpha-2": "TM" },
  { name: "Uzbekistan", "alpha-2": "UZ" },
  { name: "Venezuela, Bolivarian Republic of", "alpha-2": "VE" },
  { name: "Viet Nam", "alpha-2": "VN" },
  { name: "Zambia", "alpha-2": "ZM" },
  { name: "Zimbabwe", "alpha-2": "ZW" },
];

export const COUNTRIES: CountryOption[] = RAW.map(({ name, "alpha-2": code }) => ({ code, name })).sort((a, b) =>
  a.name.localeCompare(b.name)
);

/** Regional indicator symbols: 🇪🇬 from "EG" */
export function getFlagEmoji(code: string): string {
  if (!code || code.length !== 2) return "";
  return code
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(0x1f1e6 - 65 + c.charCodeAt(0)))
    .join("");
}
